name: mlgeo-jensencc

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - rasterio
  - xarray
  - geopandas
  - jupyterlab
  - rioxarray
  - gdal
  - earthengine-api
  - geemap
  - pip:
      - git+https://github.com/fastice/grimpfunc.git@master
      - git+https://github.com/fastice/grimpqgis.git@master
      - git+https://github.com/fastice/nisardev.git@main
      - git+https://github.com/developmentseed/rio-stac@main